/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASSIGN_H_RPCGEN
#define _ASSIGN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct my_numbers {
	int a;
	int b;
	int c;
	char msg[134];
};
typedef struct my_numbers my_numbers;

#define ADDITION 0x23451111
#define ADD_2 2

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 2
extern  int * add_2(my_numbers *, CLIENT *);
extern  int * add_2_svc(my_numbers *, struct svc_req *);
extern int addition_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 2
extern  int * add_2();
extern  int * add_2_svc();
extern int addition_2_freeresult ();
#endif /* K&R C */

#define PRODUCT 0x23452222
#define PDCT_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRDCT 1
extern  int * prdct_1(my_numbers *, CLIENT *);
extern  int * prdct_1_svc(my_numbers *, struct svc_req *);
extern int product_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRDCT 1
extern  int * prdct_1();
extern  int * prdct_1_svc();
extern int product_1_freeresult ();
#endif /* K&R C */

#define DISPLAY 0x23453333
#define DSPL_3 3

#if defined(__STDC__) || defined(__cplusplus)
#define DSPLY 3
extern  char * dsply_3(my_numbers *, CLIENT *);
extern  char * dsply_3_svc(my_numbers *, struct svc_req *);
extern int display_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DSPLY 3
extern  char * dsply_3();
extern  char * dsply_3_svc();
extern int display_3_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_my_numbers (XDR *, my_numbers*);

#else /* K&R C */
extern bool_t xdr_my_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASSIGN_H_RPCGEN */
