/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "assign.h"

bool_t
xdr_my_numbers (XDR *xdrs, my_numbers *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->a))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->b))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->a);
		IXDR_PUT_LONG(buf, objp->b);
		IXDR_PUT_LONG(buf, objp->c);
		}
		 if (!xdr_vector (xdrs, (char *)objp->msg, 134,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->a))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->b))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c))
				 return FALSE;

		} else {
		objp->a = IXDR_GET_LONG(buf);
		objp->b = IXDR_GET_LONG(buf);
		objp->c = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->msg, 134,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->msg, 134,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
